name: CI
on:
  push:
    branches: [ test-framework ]
  pull_request:
    branches: [ test-framework ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependence
        run: |
          npm i
      - name: run eslint
        run: |
          npm run lint
      - name: run test
        run: |
          npm run test